apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myextrapod1
  name: myextrapod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myextrapod1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myextrapod1
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
