apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
   name: clustergeneratorappsetlw
   namespace: argocd
spec:
  generators:
  - clusters:
       selector:
         matchLabels:
           environment: production
  template:
    metadata:
      name: '{{name}}-application'
    spec:
      project: default
      destination:
         server: '{{server}}'
         namespace: default
      source:
        repoURL:  https://github.com/vimallinuxworld13/argocd_training_2024_code.git
        path: multienv/prod-cluster
        targetRevision: master

