apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
   name: cluster-generator-appSet-lw
   namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-application'
    spec:
      project: default
      destination:
         server: '{{server}}'
         namespace: default
      source:
        repoURL:  https://github.com/vimallinuxworld13/argocd_training_2024_code.git
        path: multienv/staging
        targetRevision: master

