apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: lwwebappprod
spec:
  project: default
  destination:
    server: https://192.168.59.123:8443
    namespace: default
  source:
    repoURL:  https://github.com/vimallinuxworld13/argocd_training_2024_code.git
    path: multienv/prod
    targetRevision: master
