apiVersion: v1
kind: Secret
metadata:
  name: external-prod-cluster-lw
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: production
type: Opaque
stringData:
  name:  prod-cluster-lw
  server: https://192.168.59.123:8443 
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IkxneUJURG1Da2R2bnhKRmNoVGNXQ2NVNnlBVV9mc19KQTFpT1c3X3YzYm8ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzM0MjY5ODgyLCJpYXQiOjE3MzQyNjYyODIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNGJhY2MyNmUtMGJhOC00MDQxLTk5ODYtMWUyOGFiNTdlMWY4Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb2QtY2x1c3Rlci1zYSIsInVpZCI6IjljMzA1NjAwLTdkMTMtNDdjNi1hYWFlLTczMGNhZmNjNDdmMCJ9fSwibmJmIjoxNzM0MjY2MjgyLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpwcm9kLWNsdXN0ZXItc2EifQ.wJLUIDhESqeBiDQ0r_xoj0H3q9Mp4iZQdxsoSl7_bL-5tNB1ITD6gFWMN4N7Ye4WZbyxLmg2nL74RUiokvTH5qdIlHTrDPvvfzL6Eife9xCJ6cpl7kZ2Oh0KopmATpPWoJuze6QDiT0-gK14JPq0iSkG9enk66m0PZoqrHn30t0b3CfZ_R2ELt3_7AD4XCGHJplPBPoa2BIsEWWVi7RxsyJ33lpa4aFPM071NcozRI9m6DgJ5IGw-ga_07MpCY8fMTxTsOfKVnv6BvXasWJXz8q3tgVrFW6cX8b0BzsRp47lkKdiNs9CaZQxukQzG0B0h3WARCOnquSOkpThTI7J5A",
      "tlsClientConfig": {
          "insecure": true

      }
    }
