apiVersion: v1
kind: Secret
metadata:
  name: external-lwc2
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name:  external-lwc2-cluster
  server: https://192.168.59.117:8443 
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IndLcjM5NTFvaENUN3dHNHJUOEJHSW0zbEw2T0NmTlhPMUN3RTNmazVCeU0ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzMzNjY2MDc2LCJpYXQiOjE3MzM2NjI0NzYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMmQwY2MwNjgtN2UyYi00ZGYxLTllYmItMDZiYzg0ODZlMjc2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByb2RzYSIsInVpZCI6IjMyNjI0ZjY4LTlkODQtNDI4Ni05ZjAwLTMyNGNiYTI0MGZmYyJ9fSwibmJmIjoxNzMzNjYyNDc2LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpwcm9kc2EifQ.QBfZNUGrAY4K13x0G8eaBEl5yOuqPB0Vn6oLncI46yh0OZeeyMVMgKXtLQ2HmQHYGvAof-fwiw9WfMzuG8_uA-p-FpTOYX5v0WQedXtMz7gGZ_pT0k5GEf09Hs3U9Q3DwFl4_0XrJrYchGAN2OfxSC1DTA1vSlDP2BNCb3lLCBRMAhptMfNqRvhUbzdZW4GG2H8jLJetLKPhJXJ9rEMz0sAkiBFske5BWip9812Y2O92VYMQ3Uh9KajFD68jF3ttM9YsQD7BgBdbBIUmGrLeOCMrhN8TMa3MVStqRfU4Dx-UcEq6P648w_WOXSSduzBDp46VXpwn4lds6loWUgn3HA",
      "tlsClientConfig": {
          "insecure": true

      }
    }
